steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "asia-southeast1-docker.pkg.dev/mcp-gantt/worker-3d-scan-repo/worker-3d-scan:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "asia-southeast1-docker.pkg.dev/mcp-gantt/worker-3d-scan-repo/worker-3d-scan:latest", "us-central1-docker.pkg.dev/mcp-gantt/worker-3d-scan-us-repo/worker-3d-scan:latest"]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "us-central1-docker.pkg.dev/mcp-gantt/worker-3d-scan-us-repo/worker-3d-scan:latest"]
images:
  - "us-central1-docker.pkg.dev/mcp-gantt/worker-3d-scan-us-repo/worker-3d-scan:latest"
