steps:
  # 1. Login to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "$$DOCKER_HUB_PASS" | docker login --username=$_DOCKER_USER --password-stdin
    secretEnv: ['DOCKER_HUB_PASS']

  # 1.5 Pull the previous image to use as cache
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull $_DOCKER_USER/$_REPO_NAME:v1.0.7 || exit 0']

  # 2. Build the container image using cache-from
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--cache-from', '$_DOCKER_USER/$_REPO_NAME:v1.0.7',
      '-t', '$_DOCKER_USER/$_REPO_NAME:v1.0.8',
      '.'
    ]

  # 3. Push the container image to Docker Hub
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      '$_DOCKER_USER/$_REPO_NAME:v1.0.8'
    ]

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/docker-hub-pass/versions/latest
      env: 'DOCKER_HUB_PASS'

substitutions:
  _DOCKER_USER: ramayana4
  _REPO_NAME: worker-3d-scan

options:
  logging: CLOUD_LOGGING_ONLY
